FROM ghcr.io/cirruslabs/flutter:3.35.6 AS build
ARG MAWA_ENVIRONMENT=prod
WORKDIR /app
COPY pubspec.yaml pubspec.lock ./
RUN flutter pub get
COPY . .
RUN flutter build web --release --base-href / --dart-define=env=${MAWA_ENVIRONMENT} --dart-define=ENVIRONMENT=${MAWA_ENVIRONMENT}

FROM nginx:1.27.5-alpine
COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 8080
